### ISSUE TITLE
[Refactor] refactor code & data

### ISSUE THREAD

**Issue by psw9428** [kim-do-hyeon/TAG#37]
## 코드 리팩토링 필요

- [ ] 파일 이름 기반 priority추가
- [x] 설명 파트 디벨롭
- [x] 주석 및 필요없는 코드 삭제
- [x] progress bar 적용
- [ ] hit_id가 여러개 있는 경우 처리방법
- [ ] usb 데이터 hit_id 추가 방안 모색
- [x] 노드 아이콘 개선
- [x] 노드에 들어갈 라벨 개선
  - [ ] 로그파일 데이터 불러올 때 각각의 operation에 어떤 라벨을 넣을지 결정

**Comment by kim-do-hyeon** [comment]
ver1.7에 해당 사항 적용 완료.
